"""initial schema

Revision ID: 95d9c707ca53
Revises: 
Create Date: 2026-05-02 17:40:33.903860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d9c707ca53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lichess_username', sa.String(), nullable=False),
    sa.Column('chesscom_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lichess_username')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_game_id', sa.String(), nullable=False),
    sa.Column('user_color', sa.String(), nullable=False),
    sa.Column('white', sa.String(), nullable=False),
    sa.Column('black', sa.String(), nullable=False),
    sa.Column('white_elo', sa.Integer(), nullable=True),
    sa.Column('black_elo', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('has_evals', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'source_game_id', name='uq_game_source')
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('eval_before_cp', sa.Integer(), nullable=True),
    sa.Column('eval_after_cp', sa.Integer(), nullable=True),
    sa.Column('winrate_before', sa.Float(), nullable=False),
    sa.Column('winrate_after', sa.Float(), nullable=False),
    sa.Column('winrate_drop', sa.Float(), nullable=False),
    sa.Column('best_move_uci', sa.String(), nullable=True),
    sa.Column('best_move_san', sa.String(), nullable=True),
    sa.Column('suggested_step', sa.Integer(), nullable=True),
    sa.Column('suggestion_confidence', sa.Float(), nullable=True),
    sa.Column('suggestion_debug', sa.JSON(), nullable=True),
    sa.Column('classified_step', sa.Integer(), nullable=True),
    sa.Column('classified_awareness', sa.String(), nullable=True),
    sa.Column('time_pressure_flag', sa.Boolean(), nullable=False),
    sa.Column('transition_flag', sa.Boolean(), nullable=False),
    sa.Column('endgame_flag', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_mistake_game_ply')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('san', sa.String(), nullable=True),
    sa.Column('uci', sa.String(), nullable=True),
    sa.Column('is_user_move', sa.Boolean(), nullable=False),
    sa.Column('eval_cp', sa.Integer(), nullable=True),
    sa.Column('mate_in', sa.Integer(), nullable=True),
    sa.Column('clock_ms', sa.Integer(), nullable=True),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_position_game_ply', ['game_id', 'ply'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_position_game_ply')

    op.drop_table('positions')
    op.drop_table('mistakes')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
