"""add app_settings singleton

Revision ID: d3cd423cdc8d
Revises: 95d9c707ca53
Create Date: 2026-05-16 18:40:57.478294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd423cdc8d'
down_revision: Union[str, Sequence[str], None] = '95d9c707ca53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winrate_inaccuracy', sa.Float(), nullable=False),
    sa.Column('winrate_mistake', sa.Float(), nullable=False),
    sa.Column('winrate_blunder', sa.Float(), nullable=False),
    sa.Column('suppress_below', sa.Float(), nullable=False),
    sa.Column('suppress_above_before', sa.Float(), nullable=False),
    sa.Column('suppress_above_after', sa.Float(), nullable=False),
    sa.Column('lichess_study_ids', sa.JSON(), nullable=False),
    sa.Column('study_player_aliases', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
